<?php

namespace Database\Seeders;

use App\Models\VolunteerAchievement;
use Illuminate\Database\Seeder;

class VolunteerAchievementsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $achievements = [
            // Hours-based achievements
            [
                'name' => 'First Steps',
                'slug' => 'first-steps',
                'description' => 'Complete your first volunteer hour and begin your journey of making a difference.',
                'icon' => 'fas fa-baby',
                'badge_color' => 'green',
                'type' => 'hours',
                'criteria' => ['hours' => 1, 'operator' => '>='],
                'points' => 10,
                'sort_order' => 1,
            ],
            [
                'name' => 'Getting Started',
                'slug' => 'getting-started',
                'description' => 'Reach 10 volunteer hours and show your commitment to community service.',
                'icon' => 'fas fa-seedling',
                'badge_color' => 'green',
                'type' => 'hours',
                'criteria' => ['hours' => 10, 'operator' => '>='],
                'points' => 25,
                'sort_order' => 2,
            ],
            [
                'name' => 'Quarter Century',
                'slug' => 'quarter-century',
                'description' => 'Complete 25 hours of volunteer service and demonstrate your growing dedication.',
                'icon' => 'fas fa-leaf',
                'badge_color' => 'green',
                'type' => 'hours',
                'criteria' => ['hours' => 25, 'operator' => '>='],
                'points' => 50,
                'sort_order' => 3,
            ],
            [
                'name' => 'Half Century',
                'slug' => 'half-century',
                'description' => 'Achieve 50 volunteer hours and show substantial commitment to your community.',
                'icon' => 'fas fa-tree',
                'badge_color' => 'blue',
                'type' => 'hours',
                'criteria' => ['hours' => 50, 'operator' => '>='],
                'points' => 100,
                'sort_order' => 4,
            ],
            [
                'name' => 'Century Club',
                'slug' => 'century-club',
                'description' => 'Join the exclusive Century Club with 100 hours of volunteer service.',
                'icon' => 'fas fa-medal',
                'badge_color' => 'blue',
                'type' => 'hours',
                'criteria' => ['hours' => 100, 'operator' => '>='],
                'points' => 200,
                'sort_order' => 5,
            ],
            [
                'name' => 'Dedicated Volunteer',
                'slug' => 'dedicated-volunteer',
                'description' => 'Reach 250 volunteer hours and prove your exceptional dedication.',
                'icon' => 'fas fa-star',
                'badge_color' => 'purple',
                'type' => 'hours',
                'criteria' => ['hours' => 250, 'operator' => '>='],
                'points' => 500,
                'sort_order' => 6,
            ],
            [
                'name' => 'Community Champion',
                'slug' => 'community-champion',
                'description' => 'Complete 500 hours of volunteer service and become a true community champion.',
                'icon' => 'fas fa-trophy',
                'badge_color' => 'yellow',
                'type' => 'hours',
                'criteria' => ['hours' => 500, 'operator' => '>='],
                'points' => 1000,
                'sort_order' => 7,
            ],
            [
                'name' => 'Volunteer Legend',
                'slug' => 'volunteer-legend',
                'description' => 'Achieve legendary status with 1000+ hours of volunteer service.',
                'icon' => 'fas fa-crown',
                'badge_color' => 'yellow',
                'type' => 'hours',
                'criteria' => ['hours' => 1000, 'operator' => '>='],
                'points' => 2000,
                'sort_order' => 8,
            ],

            // Assignment-based achievements
            [
                'name' => 'Mission Complete',
                'slug' => 'mission-complete',
                'description' => 'Successfully complete your first volunteer assignment.',
                'icon' => 'fas fa-check-circle',
                'badge_color' => 'green',
                'type' => 'assignments',
                'criteria' => ['assignments' => 1, 'operator' => '>='],
                'points' => 15,
                'sort_order' => 10,
            ],
            [
                'name' => 'Multi-Tasker',
                'slug' => 'multi-tasker',
                'description' => 'Complete 5 different volunteer assignments and show your versatility.',
                'icon' => 'fas fa-tasks',
                'badge_color' => 'blue',
                'type' => 'assignments',
                'criteria' => ['assignments' => 5, 'operator' => '>='],
                'points' => 75,
                'sort_order' => 11,
            ],
            [
                'name' => 'Assignment Master',
                'slug' => 'assignment-master',
                'description' => 'Complete 10 volunteer assignments and master the art of service.',
                'icon' => 'fas fa-clipboard-check',
                'badge_color' => 'purple',
                'type' => 'assignments',
                'criteria' => ['assignments' => 10, 'operator' => '>='],
                'points' => 150,
                'sort_order' => 12,
            ],
            [
                'name' => 'Serial Volunteer',
                'slug' => 'serial-volunteer',
                'description' => 'Complete 25 volunteer assignments and become a serial do-gooder.',
                'icon' => 'fas fa-list-check',
                'badge_color' => 'indigo',
                'type' => 'assignments',
                'criteria' => ['assignments' => 25, 'operator' => '>='],
                'points' => 375,
                'sort_order' => 13,
            ],

            // Organization-based achievements
            [
                'name' => 'Organization Explorer',
                'slug' => 'organization-explorer',
                'description' => 'Volunteer with 3 different organizations and explore diverse causes.',
                'icon' => 'fas fa-compass',
                'badge_color' => 'blue',
                'type' => 'organizations',
                'criteria' => ['organizations' => 3, 'operator' => '>='],
                'points' => 100,
                'sort_order' => 20,
            ],
            [
                'name' => 'Cause Connector',
                'slug' => 'cause-connector',
                'description' => 'Support 5 different organizations and connect with various causes.',
                'icon' => 'fas fa-network-wired',
                'badge_color' => 'purple',
                'type' => 'organizations',
                'criteria' => ['organizations' => 5, 'operator' => '>='],
                'points' => 200,
                'sort_order' => 21,
            ],
            [
                'name' => 'Community Networker',
                'slug' => 'community-networker',
                'description' => 'Volunteer with 10 different organizations and build a strong community network.',
                'icon' => 'fas fa-handshake',
                'badge_color' => 'indigo',
                'type' => 'organizations',
                'criteria' => ['organizations' => 10, 'operator' => '>='],
                'points' => 500,
                'sort_order' => 22,
            ],

            // Skills-based achievements
            [
                'name' => 'Skilled Helper',
                'slug' => 'skilled-helper',
                'description' => 'Use your professional skills to help others through skilled volunteering.',
                'icon' => 'fas fa-tools',
                'badge_color' => 'blue',
                'type' => 'skills',
                'criteria' => ['skills' => ['Professional Skills', 'Technical Skills'], 'require_all' => false],
                'points' => 75,
                'sort_order' => 30,
            ],
            [
                'name' => 'Teaching Spirit',
                'slug' => 'teaching-spirit',
                'description' => 'Share your knowledge by volunteering in education and training.',
                'icon' => 'fas fa-chalkboard-teacher',
                'badge_color' => 'green',
                'type' => 'skills',
                'criteria' => ['skills' => ['Teaching', 'Training', 'Education'], 'require_all' => false],
                'points' => 100,
                'sort_order' => 31,
            ],
            [
                'name' => 'Creative Contributor',
                'slug' => 'creative-contributor',
                'description' => 'Use your creative talents to make a difference in the community.',
                'icon' => 'fas fa-palette',
                'badge_color' => 'pink',
                'type' => 'skills',
                'criteria' => ['skills' => ['Arts & Crafts', 'Design', 'Photography', 'Writing'], 'require_all' => false],
                'points' => 100,
                'sort_order' => 32,
            ],

            // Special achievements
            [
                'name' => 'Welcome Aboard',
                'slug' => 'welcome-aboard',
                'description' => 'Submit your first volunteer application and join our community.',
                'icon' => 'fas fa-hand-wave',
                'badge_color' => 'green',
                'type' => 'special',
                'criteria' => ['special_type' => 'first_application'],
                'points' => 5,
                'sort_order' => 40,
            ],
            [
                'name' => 'Finisher',
                'slug' => 'finisher',
                'description' => 'Complete your first volunteer assignment from start to finish.',
                'icon' => 'fas fa-flag-checkered',
                'badge_color' => 'blue',
                'type' => 'special',
                'criteria' => ['special_type' => 'first_completion'],
                'points' => 25,
                'sort_order' => 41,
            ],
            [
                'name' => 'Consistent Contributor',
                'slug' => 'consistent-contributor',
                'description' => 'Volunteer for 3 consecutive months and show consistent commitment.',
                'icon' => 'fas fa-calendar-check',
                'badge_color' => 'purple',
                'type' => 'special',
                'criteria' => ['special_type' => 'consecutive_months', 'months' => 3],
                'points' => 150,
                'sort_order' => 42,
            ],
            [
                'name' => 'Long-term Commitment',
                'slug' => 'long-term-commitment',
                'description' => 'Volunteer for 6 consecutive months and demonstrate long-term commitment.',
                'icon' => 'fas fa-calendar-alt',
                'badge_color' => 'indigo',
                'type' => 'special',
                'criteria' => ['special_type' => 'consecutive_months', 'months' => 6],
                'points' => 300,
                'sort_order' => 43,
            ],
            [
                'name' => 'Year-Round Volunteer',
                'slug' => 'year-round-volunteer',
                'description' => 'Volunteer for 12 consecutive months and become a year-round volunteer.',
                'icon' => 'fas fa-calendar',
                'badge_color' => 'yellow',
                'type' => 'special',
                'criteria' => ['special_type' => 'consecutive_months', 'months' => 12],
                'points' => 600,
                'sort_order' => 44,
            ],
            [
                'name' => 'Weekend Warrior',
                'slug' => 'weekend-warrior',
                'description' => 'Frequently volunteer on weekends and maximize your impact.',
                'icon' => 'fas fa-calendar-week',
                'badge_color' => 'red',
                'type' => 'special',
                'criteria' => ['special_type' => 'weekend_warrior'],
                'points' => 200,
                'sort_order' => 45,
            ],

            // Milestone achievements
            [
                'name' => 'Rising Star',
                'slug' => 'rising-star',
                'description' => 'Earn your first 100 achievement points and become a rising star.',
                'icon' => 'fas fa-star-half-alt',
                'badge_color' => 'yellow',
                'type' => 'special',
                'criteria' => ['special_type' => 'achievement_points', 'points' => 100],
                'points' => 50,
                'sort_order' => 50,
            ],
            [
                'name' => 'Point Collector',
                'slug' => 'point-collector',
                'description' => 'Accumulate 500 achievement points through various accomplishments.',
                'icon' => 'fas fa-coins',
                'badge_color' => 'yellow',
                'type' => 'special',
                'criteria' => ['special_type' => 'achievement_points', 'points' => 500],
                'points' => 100,
                'sort_order' => 51,
            ],
            [
                'name' => 'Achievement Hunter',
                'slug' => 'achievement-hunter',
                'description' => 'Earn 1000 achievement points and become a true achievement hunter.',
                'icon' => 'fas fa-trophy',
                'badge_color' => 'yellow',
                'type' => 'special',
                'criteria' => ['special_type' => 'achievement_points', 'points' => 1000],
                'points' => 200,
                'sort_order' => 52,
            ],

            // Community impact achievements
            [
                'name' => 'Impact Maker',
                'slug' => 'impact-maker',
                'description' => 'Make a significant impact by helping multiple beneficiaries.',
                'icon' => 'fas fa-heart',
                'badge_color' => 'red',
                'type' => 'special',
                'criteria' => ['special_type' => 'impact_maker'],
                'points' => 150,
                'sort_order' => 60,
            ],
            [
                'name' => 'Community Builder',
                'slug' => 'community-builder',
                'description' => 'Help build stronger communities through your volunteer efforts.',
                'icon' => 'fas fa-building',
                'badge_color' => 'blue',
                'type' => 'special',
                'criteria' => ['special_type' => 'community_builder'],
                'points' => 200,
                'sort_order' => 61,
            ],
            [
                'name' => 'Change Agent',
                'slug' => 'change-agent',
                'description' => 'Be an agent of positive change in your community.',
                'icon' => 'fas fa-exchange-alt',
                'badge_color' => 'purple',
                'type' => 'special',
                'criteria' => ['special_type' => 'change_agent'],
                'points' => 250,
                'sort_order' => 62,
            ],

            // Leadership achievements
            [
                'name' => 'Team Player',
                'slug' => 'team-player',
                'description' => 'Work effectively as part of volunteer teams.',
                'icon' => 'fas fa-users',
                'badge_color' => 'blue',
                'type' => 'special',
                'criteria' => ['special_type' => 'team_player'],
                'points' => 100,
                'sort_order' => 70,
            ],
            [
                'name' => 'Mentor',
                'slug' => 'mentor',
                'description' => 'Guide and mentor new volunteers in their journey.',
                'icon' => 'fas fa-user-graduate',
                'badge_color' => 'green',
                'type' => 'special',
                'criteria' => ['special_type' => 'mentor'],
                'points' => 200,
                'sort_order' => 71,
            ],
            [
                'name' => 'Volunteer Leader',
                'slug' => 'volunteer-leader',
                'description' => 'Take on leadership roles in volunteer activities.',
                'icon' => 'fas fa-user-tie',
                'badge_color' => 'indigo',
                'type' => 'special',
                'criteria' => ['special_type' => 'volunteer_leader'],
                'points' => 300,
                'sort_order' => 72,
            ],

            // Recognition achievements
            [
                'name' => 'Appreciated Volunteer',
                'slug' => 'appreciated-volunteer',
                'description' => 'Receive positive feedback and appreciation from organizations.',
                'icon' => 'fas fa-thumbs-up',
                'badge_color' => 'green',
                'type' => 'special',
                'criteria' => ['special_type' => 'appreciated_volunteer'],
                'points' => 100,
                'sort_order' => 80,
            ],
            [
                'name' => 'Highly Recommended',
                'slug' => 'highly-recommended',
                'description' => 'Receive multiple recommendations from organizations you have helped.',
                'icon' => 'fas fa-certificate',
                'badge_color' => 'blue',
                'type' => 'special',
                'criteria' => ['special_type' => 'highly_recommended'],
                'points' => 200,
                'sort_order' => 81,
            ],
            [
                'name' => 'Outstanding Volunteer',
                'slug' => 'outstanding-volunteer',
                'description' => 'Be recognized as an outstanding volunteer by multiple organizations.',
                'icon' => 'fas fa-award',
                'badge_color' => 'yellow',
                'type' => 'special',
                'criteria' => ['special_type' => 'outstanding_volunteer'],
                'points' => 500,
                'sort_order' => 82,
            ],
        ];

        foreach ($achievements as $achievementData) {
            VolunteerAchievement::updateOrCreate(
                ['slug' => $achievementData['slug']],
                $achievementData
            );
        }

        $this->command->info('Volunteer achievements seeded successfully!');
    }
}